SELECT User, Host FROM mysql.user;

DROP USER 'root'@'142.93.199.193 ';

CREATE USER 'root'@'%' IDENTIFIED BY 'sSeCr4t100114';

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;

